version: '3'
services:

  enalyzer-py:
    build: .
    container_name: enalyzer-py
    restart: unless-stopped
    ports:
        - "80"
    environment:
        DJANGO_DEBUG: 'False'
        DJANGO_LOG_LEVEL: INFO
        DJANGO_ALLOWED_HOSTS: enalyzer-py
        MODEL_MAX_ENTITIES_FILTER: 10000
        STORAGE_DIR: /storage
        KEEP_UPLOADED: 5400
        KEEP_GENERATED: 600
        CACHE_BIGG: 86400
        CACHE_BIGG_MODEL: 604800
        CACHE_BIOMODELS: 86400
        CACHE_BIOMODELS_MODEL: 432000
        MAX_ENTITIES_FILTER: 10000
    volumes:
        - ./src:/code
        # optionally also mount a directory to /storage (see STORAGE_DIR above)
        # to get persistent storage even after the container is rebuilt
    logging:
        driver: syslog
            options:
                # see https://binfalse.de/2018/02/21/logging-with-docker/
                tag: docker/web/enalyzer/app


  enalyzer-web:
    image: nginx
    container_name: enalyzer-web
    restart: unless-stopped
    depends_on:
        - enalyzer-py
    ports:
        - "80:80"
    # enable the following if using nginx-proxy (https://hub.docker.com/r/binfalse/nginx-proxy/)
    # environment:
        # VIRTUAL_HOST: www.url.to.this.website
    volumes:
        - ./src/static:/var/www/static
        - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
        driver: syslog
            options:
                # see https://binfalse.de/2018/02/21/logging-with-docker/
                tag: docker/web/enalyzer/nginx
