version: '3'
services:

  gemtractor-py:
    build: .
    container_name: gemtractor-py
    restart: unless-stopped
    ports:
        - "80"
    environment:
        # see https://gemtractor.bio.informatik.uni-rostock.de/learn#own-settings
        DJANGO_DEBUG: 'False'
        DJANGO_LOG_LEVEL: INFO
        DJANGO_ALLOWED_HOSTS: gemtractor-py
        STORAGE_DIR: /storage
        KEEP_UPLOADED: 5400
        KEEP_GENERATED: 600
        CACHE_BIGG: 86400
        CACHE_BIGG_MODEL: 604800
        CACHE_BIOMODELS: 86400
        CACHE_BIOMODELS_MODEL: 432000
        MAX_ENTITIES_FILTER: 10000
        HEALTH_SECRET: XXX
    volumes:
        - ./src:/code
        # optionally also mount a directory to /storage (see STORAGE_DIR above)
        # to get persistent storage even after the container is rebuilt
    logging:
        driver: syslog
            options:
                # see https://binfalse.de/2018/02/21/logging-with-docker/
                tag: docker/web/gemtractor/app


  gemtractor-web:
    image: nginx
    container_name: gemtractor-web
    restart: unless-stopped
    depends_on:
        - gemtractor-py
    ports:
        - "80:80"
    volumes:
        - ./src/static:/var/www/static
        - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
        driver: syslog
            options:
                # see https://binfalse.de/2018/02/21/logging-with-docker/
                tag: docker/web/gemtractor/nginx
